Repository LessonsQueue/QueueManagerFront, pull requests merged in 2024-05, with the labels that each got.

#1 Added basic structure
  src/app.html
  src/components/Content.svelte
  src/components/Day.svelte
  src/components/Footer.svelte
  src/components/Header.svelte
  src/mockData.js
  src/routes/+page.svelte
Labels: enhancement

#4 Added queue button
  src/components/Queue.svelte
Labels: enhancement

#8 feature: added github actions file for build the app
  .github/workflows/build.yml
Labels: feature

#9 Added component for messages
  src/components/Message.svelte
Labels: feature

#7 Implement register and login
  src/auth.js
  src/components/Auth/Auth.svelte
  src/components/Auth/SignUpForm.svelte
Labels: feature

#10 Added usage of messages
  src/components/Auth/Auth.svelte
  src/components/Message.svelte
  src/messageStore.js
  src/routes/+page.svelte
Labels: enhancement

#11 Feature/added dockerfile
  .dockerignore
  Dockerfile
Labels: feature

#12 documentation/added-readme
  .dockerignore
  README.md
Labels: documentation

#13 More buttons for queue managment
  src/components/Message.svelte
  src/components/Queue.svelte
  src/routes/+page.svelte
Labels: enhancement
